"""Render an HTML artifact to PDF via headless chromium.

Why this lives in artifold instead of being "just Cmd+P":
  - one-click from the dashboard, no print dialog drilling
  - artifacts generated by /craft ship with `@media print` rules tuned
    per design mode (so output matches the screen, not the AI-default
    "white margins and a broken layout" Cmd+P result)
  - multi-file projects (sibling CSS/JS, CDN fonts) render correctly
    because Playwright loads via file:// which resolves siblings, and
    networkidle waits for CDN fonts before the snapshot
  - the export gets recorded in provenance so the artifact lifecycle
    (generate → index → share/export) is traceable

Output path policy:
  1. Try next to the source: `<source-dir>/<stem>.pdf`
  2. If the source dir isn't writable (read-only, permission denied),
     fall back to `~/Downloads/<stem>-<short-sha>.pdf`
  3. Existing files at the target are overwritten (idempotent re-exports
     produce a stable path); a one-time backup is NOT created — the
     source HTML is the canonical artifact, the PDF is derivative.
"""
from __future__ import annotations

import asyncio
import os
from pathlib import Path
from typing import Literal

from . import provenance

# A4 and US Letter cover most printing needs; legal/tabloid for the odd case.
VALID_FORMATS = {"A4", "Letter", "Legal", "Tabloid", "A3", "A5"}

# Reasonable defaults. Backgrounds ON because most artifacts deliberately
# use colored fills (museum-label off-white, monochrome-poster black,
# terminal-tui dark) — printing them as pure-white-and-black destroys
# the design intent.
DEFAULTS = {
    "format": "A4",
    "landscape": False,
    "print_backgrounds": True,
    "margin": "12mm",     # generous default; users almost always want margins
}


def _default_pdf_path(html_path: Path) -> Path:
    """Where to write the PDF. Tries next-to-source, falls back to ~/Downloads."""
    stem = html_path.stem
    src_dir = html_path.parent
    # Quick writability probe — avoids a sketchy try-write-then-cleanup dance
    if os.access(src_dir, os.W_OK):
        return src_dir / f"{stem}.pdf"
    # Fall back to ~/Downloads with a short-sha suffix (avoids collisions
    # when multiple read-only artifacts share a stem)
    downloads = Path.home() / "Downloads"
    if not downloads.is_dir():
        # No Downloads dir (some Linux setups) — last resort: /tmp
        downloads = Path("/tmp")
    short = provenance.sha1_of(html_path)[:8]
    return downloads / f"{stem}-{short}.pdf"


async def _render_pdf(html_path: Path, out: Path, *, format: str,
                      landscape: bool, print_backgrounds: bool,
                      margin: str) -> Path:
    # Share the same "auto-install chromium on first use" logic as scan/shoot —
    # otherwise a fresh `pip install artifold` user's first PDF export fails
    # with a cryptic "BrowserType.launch: Executable doesn't exist" error.
    from .shoot import ensure_chromium
    if not ensure_chromium():
        raise RuntimeError("could not install playwright chromium - try: "
                           "python -m playwright install chromium-headless-shell")
    from playwright.async_api import async_playwright
    async with async_playwright() as pw:
        browser = await pw.chromium.launch()
        try:
            page = await browser.new_page(viewport={"width": 1280, "height": 800})
            # networkidle catches CDN font/CSS loads that pure "load" misses;
            # fall back to "load" if a long-poll socket prevents idle.
            try:
                await page.goto(html_path.as_uri(),
                                wait_until="networkidle", timeout=15000)
            except Exception:
                await page.goto(html_path.as_uri(),
                                wait_until="load", timeout=20000)
            # Settle: let JS hydration / web fonts / late paints finish.
            await page.wait_for_timeout(1500)
            # Force print media so `@media print { ... }` rules apply (matches
            # what the user would see in Cmd+P preview, not the screen view).
            await page.emulate_media(media="print")
            out.parent.mkdir(parents=True, exist_ok=True)
            await page.pdf(
                path=str(out),
                format=format,
                landscape=landscape,
                print_background=print_backgrounds,
                margin={"top": margin, "right": margin, "bottom": margin, "left": margin},
                prefer_css_page_size=True,
            )
        finally:
            await browser.close()
    return out


def export_pdf(html_path: Path, *,
               out: Path | None = None,
               format: Literal["A4", "Letter", "Legal", "Tabloid", "A3", "A5"] = "A4",
               landscape: bool = False,
               print_backgrounds: bool = True,
               margin: str = "12mm",
               record_provenance: bool = True) -> Path:
    """Render `html_path` to a PDF file. Returns the output path.

    Raises ValueError for unsupported format, FileNotFoundError if html_path
    doesn't exist, RuntimeError if playwright is missing or chromium fails.
    """
    if format not in VALID_FORMATS:
        raise ValueError(f"format must be one of {sorted(VALID_FORMATS)}, got {format!r}")
    html_path = html_path.expanduser().resolve()
    if not html_path.is_file():
        raise FileNotFoundError(f"not a file: {html_path}")
    if out is None:
        out = _default_pdf_path(html_path)
    out = Path(out).expanduser().resolve()

    try:
        asyncio.run(_render_pdf(html_path, out,
                                format=format, landscape=landscape,
                                print_backgrounds=print_backgrounds,
                                margin=margin))
    except ImportError as e:
        raise RuntimeError(
            "playwright not installed — pip install playwright "
            "&& python -m playwright install chromium") from e

    if record_provenance:
        try:
            sha = provenance.sha1_of(html_path)
            entry = provenance.get(sha) or {}
            exports = list(entry.get("exports") or [])
            exports.append({
                "format": "pdf",
                "page_size": format,
                "landscape": landscape,
                "path": str(out),
                "size": out.stat().st_size,
                "created_at": provenance._now(),
            })
            provenance.set_(sha, exports=exports)
        except Exception:
            pass  # provenance is best-effort; never fail the export over it

    return out
